name: Daily News Digest
on:
  workflow_dispatch:
jobs:
  news-digest:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "hello world"
      - name: Send
        run: curl -s -X POST "https://www.pushplus.plus/send" -H "Content-Type: application/json" -d '{"token":"4b14ad2c8062439f804d3886e8a87d99","title":"测试","content":"GitHub Actions 跑通了 ✅","template":"html"}'
